### ISSUE TITLE
bug: Routes cannot bind plugins

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix-dashboard#102]
### Issue description

![image](https://user-images.githubusercontent.com/3816205/71351557-f8630e80-25ae-11ea-86ce-6dd9fa6f88c2.png)

I created a route. When binding the plugin, I chose the serverless-pre-function plugin. Then, instead of clicking Confirm, I clicked the Cancel button. When I chose another plugin, I found unable to bind other plugin.

### Environment

* apisix version (cmd: `apisix version`): master
* OS: linux

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/incubator-apisix-dashboard/issues/36

**Comment by juzhiyuan** [comment]
would be fixed #188
