### ISSUE TITLE
Plugin proxy-rewrite 保存异常

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#107]
![image](https://user-images.githubusercontent.com/28976666/71430085-edba8d80-2704-11ea-8916-8a9e3ace38a4.png)
![image](https://user-images.githubusercontent.com/28976666/71430104-062aa800-2705-11ea-8f5d-e11a9558eacd.png)
![image](https://user-images.githubusercontent.com/28976666/71430113-0e82e300-2705-11ea-9b81-650d7634cea2.png)
按照上述流程，先编辑保存，再编辑删除url保存报错

**Comment by jiezaizone** [comment]
![image](https://user-images.githubusercontent.com/28976666/71432777-b2c15580-2716-11ea-9b6d-cdc8e7592a43.png)

**Comment by juzhiyuan** [comment]
would be fixed #188
