### ISSUE TITLE
openid-connect Plugin 点击一次后关闭，再点击弹窗就出不来了

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#113]
![image](https://user-images.githubusercontent.com/28976666/71763255-c63d9f00-2f14-11ea-8fa9-cca0062ebb8d.png)
`openid-connect Plugin` 点击一次后关闭，再点击弹窗就出不来了

**Comment by juzhiyuan** [comment]
would be fixed #188
