### ISSUE TITLE
Plugin openid-connect Edit 编辑bearer_only 、ssl_verify 保存按钮不可点击

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#114]
![image](https://user-images.githubusercontent.com/28976666/71763443-ebcba800-2f16-11ea-9d72-ef070784e6dc.png)
Plugin openid-connect Edit 编辑bearer_only 、ssl_verify 保存按钮不可点击

**Comment by juzhiyuan** [comment]
would be fixed #188
