### ISSUE TITLE
SSL编辑时候，原有key是否应该不可见？出于安全性考虑

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#115]
![image](https://user-images.githubusercontent.com/28976666/71763822-71e9ed80-2f1b-11ea-84e0-04387967d970.png)
SSL编辑时候，原有key是否应该不可见？出于安全性考虑，可以编辑但不反显。

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/incubator-apisix/issues/994
