### ISSUE TITLE
upstream  page displays table  error

### ISSUE THREAD

**Issue by aimpsmile** [apache/incubator-apisix-dashboard#116]
eg:
`json
{
    "node": {
        "nodes": [
            {
                "value": {
                    "nodes": {
                        "nodejs.service:3000": 1
                    },
                    "desc": "yapi",
                    "type": "roundrobin"
                },
                "createdIndex": 173,
                "key": "/apisix/upstreams/00000000000000000164",
                "modifiedIndex": 173
            },
            {
                "value": {
                    "nodes": {
                        "go.service:33902": 1
                    },
                    "desc": "grpc~test",
                    "type": "roundrobin"
                },
                "createdIndex": 192,
                "key": "/apisix/upstreams/00000000000000000192",
                "modifiedIndex": 192
            },
            {
                "value": {
                    "desc": "test~upstream",
                    "nodes": {
                        "127.0.0.2:81": 2,
                        "foo.com:80": 3,
                        "remote-local.test:80": 1
                    },
                    "type": "roundrobin"
                },
                "createdIndex": 329,
                "key": "/apisix/upstreams/00000000000000000328",
                "modifiedIndex": 329
            },
            {
                "value": {
                    "nodes": {
                        "nodejs.service:9090": 1
                    },
                    "desc": "yapiinstall",
                    "type": "roundrobin"
                },
                "createdIndex": 163,
                "key": "/apisix/upstreams/00000000000000000139",
                "modifiedIndex": 163
            }
        ],
        "modifiedIndex": 129,
        "createdIndex": 129,
        "key": "/apisix/upstreams",
        "dir": true
    },
    "action": "get"
}
`

page display eg:
![{F9F1134F-9295-4652-A2B3-B666CC8C48C0}_20200106200907](https://user-images.githubusercontent.com/8934904/71817348-89161000-30c0-11ea-96f3-1929f1fd53eb.jpg)

apisix server ver 0.9
apisi dashboard ver 0.9

**Comment by juzhiyuan** [comment]
Hi, I'd love to know which browser are you using?

**Comment by aimpsmile** [comment]
![{897FBDDB-5768-4064-9017-7AB852C74025}_20200107100939](https://user-images.githubusercontent.com/8934904/71862771-df716600-3135-11ea-8abc-c300609c9e63.jpg)

**Comment by juzhiyuan** [comment]
I think the green background is related to some Chrome extensions, could you please have a try on Privacy mode? for no extensions will execute in Privacy mode.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/71865513-f451f780-313d-11ea-83d9-e11e7e6e3df8.png)

**Comment by aimpsmile** [comment]
Ok. I do try

**Comment by aimpsmile** [comment]
![{61A42D2D-5284-46A3-9079-12FCBA9ABAB9}_20200107131017](https://user-images.githubusercontent.com/8934904/71870001-36376980-314f-11ea-9693-7f5398957911.jpg)
have not changed. It's the same on your side？

**Comment by aimpsmile** [comment]
I add second node or more  on upstreams are displays error,only one nodes displays not are problume .

**Comment by juzhiyuan** [comment]
I see... I thought your question is why the browser is in Green background..

Please use the latest codes from master branch instead, if you could not build the Dashboard, I'm glad to help you.

**Comment by juzhiyuan** [comment]
[dashboard.tar.gz](https://github.com/apache/incubator-apisix-dashboard/files/4029142/dashboard.tar.gz)

You could use this latest dashboard.

**Comment by aimpsmile** [comment]
thanks. I have a try

**Comment by aimpsmile** [comment]
So good. now not problem

**Comment by juzhiyuan** [comment]
Thanks for your issues found :)
