### ISSUE TITLE
hosts contains a `null` value when creating routes

### ISSUE THREAD

**Issue by masterclock** [apache/incubator-apisix-dashboard#119]
![image](https://user-images.githubusercontent.com/4335809/72677992-d50f7e80-3adc-11ea-8dc0-3cbe26a9dbf9.png)

saving results error message:
```
invalid configuration: property "hosts" validation failed: failed to validate item 1: wrong type: expected string, got userdata
```

by inspecting the api call payload:
```json
{"uris":["/testgw1"],"hosts":[null,"examples.com"],"upstream_id":"00000000000000000014","methods":["GET"],"plugins":{},"desc":"testgw1"}
```

note there's a null in hosts

**Comment by juzhiyuan** [comment]
Could you please take a look at the new Dashboard?
