### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by agile6v** [apache/incubator-apisix-dashboard#122]
Hi 
I have a few suggestions that are not necessarily right, for reference only.

1. New form page (such as:  routes, upstreams, services, ssl, consumers) can be center-aligned.
2. If the node option is required, it can be displayed directly, other pages are similar.

> Like the below:
![image](https://user-images.githubusercontent.com/2017491/72997012-a247ec00-3e36-11ea-9a47-f18111ff8ebc.png)

3. The layout is too compact.
![image](https://user-images.githubusercontent.com/2017491/72997742-acb6b580-3e37-11ea-9731-8435a9885503.png)

Thanks.

**Comment by juzhiyuan** [comment]
Will do in the next dashboard.
