### ISSUE TITLE
没有登录验证，不能修改用户密码

### ISSUE THREAD

**Issue by xzy1586** [apache/incubator-apisix-dashboard#126]
没有登录验证，不能修改用户密码

**Comment by juzhiyuan** [comment]
There has no auth logic currently on Frontend, but you could modify the `login` logic manually. And APISIX is considering to implement the auth by Token check.

**Comment by juzhiyuan** [comment]
We could use https://github.com/apache/incubator-apisix-dashboard/issues/137 in next version.

**Comment by juzhiyuan** [comment]
Support API Key check currently
