### ISSUE TITLE
The navigation bar is not visible

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#133]
![image](https://user-images.githubusercontent.com/28976666/75942155-a1da5080-5ecc-11ea-8c3a-fa1bfe20687e.png)
The navigation bar is not visible and does not shrink, but it is clickable

**Comment by juzhiyuan** [comment]
related issue and will be fixed on next version.

https://github.com/apache/incubator-apisix-dashboard/issues/124
