### ISSUE TITLE
We're sorry but Dashboard for APISIX doesn't work properly without JavaScript enabled. Please enable it to continue.

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#134]
![image](https://user-images.githubusercontent.com/28976666/75942237-d64e0c80-5ecc-11ea-9c0d-e348cbc9c3d3.png)
When the project runs after build, "We're sorry but Dashboard for APISIX doesn't work without JavaScript enabled. Please enable it to continue."
The browser supports script, so it is normal to run the server directly.

**Comment by juzhiyuan** [comment]
This issue occurred on your server side, whenever you are trying to preview the PAGE html, it will show this tip.

**Comment by juzhiyuan** [comment]
Please check your server configuration carefully, or I could help you by screen sharing when you have time.

**Comment by spfyoung** [comment]
@juzhiyuan I have the same issue now, How did you fixed it?

**Comment by juzhiyuan** [comment]
This page will always be shown whenever we preview it in the development tool, could you please some screenshot or more detailed info?

**Comment by spfyoung** [comment]
@juzhiyuan Right now I have install the dashboard follow the guide on Github, 
![apisix](https://user-images.githubusercontent.com/3838455/85404576-b7fe4080-b591-11ea-8452-7347b6af49bb.jpg)
and set the  allow_admin for ip address already, but I can not access the dashboard.

**Comment by juzhiyuan** [comment]
Not sure what happened but looks like the issue is related with your server configuration 🤔 Manager API issue should get help from @gxthrj
