### ISSUE TITLE
Complete the License information for the next dashboard

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#136]
We are building the next dashboard based on Ant Design Pro, which is an Open Source project for building awesome dashboard. We need your help to add the License to the following files under `next` branch, just like [1], but be carefully, we should use [2] this one instead. Please send a PR once you complete this issue.

1. Please create the `LICENSE` file under `next` branch, the content should be like [3]. Please note, the last two lines should be 
```
The Apache APISIX project bundles ant-design-pro under the MIT license.
For details, see licenses/LICENSE.ant-design-pro.
```
2. Please create the `/licenses/LICENSE.ALv2` file, the content should be like [4].
3. Please create the `LICENSE.ant-design-pro` file, the content should be like [2].

[1] https://github.com/apache/incubator-apisix-dashboard/blob/b3045dd2021e50d7d9943f22aae6ca7e080a15b8/src/views/login/index.vue#L1
[2] https://github.com/ant-design/ant-design-pro/blob/master/LICENSE
[3] https://github.com/apache/incubator-apisix-dashboard/blob/master/LICENSE
[4] https://github.com/apache/incubator-apisix-dashboard/blob/master/licenses/LICENSE.ALv2

**Comment by juzhiyuan** [comment]
@moonming The dashboard boilerplate is under MIT License, I'm not sure if we need add MIT License to them?

**Comment by moonming** [comment]
yes, we need add the license for it.

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年3月10日周二 上午10:47写道：

**Comment by juzhiyuan** [comment]
Just for sure, which files should add the MIT header? We would use nearly all of them.

**Comment by moonming** [comment]
here is a example:
https://github.com/apache/incubator-apisix-dashboard/blob/master/LICENSE#L205

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年3月10日周二 上午10:57写道：

**Comment by juzhiyuan** [comment]
Oh I see, so we don't have to add MIT header for every file under `next` branch? Just add the License line in `LICENSE` file?

**Comment by moonming** [comment]
yes, you are right.

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年3月10日周二 上午11:04写道：

**Comment by juzhiyuan** [comment]
@moonming Just updated the issue#1, please take a look when you are free.

**Comment by juzhiyuan** [comment]
Please refer https://github.com/apache/incubator-apisix-dashboard/issues/136#issue-578300848
