### ISSUE TITLE
Adding X-API-KEY for api request

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#137]
Our API for dashboard is using API Key to auth the request, please add the API Key Header in global request handler. Just like [1] for reference. Please note, this key should be added by `config` file, such as `.env` file. I recommend fetching this key by `fetchAPIKey` API.

[1] https://github.com/apache/incubator-apisix-dashboard/commit/b3b306550e8e5153d42d943d2d652914e2ad88e3#diff-084c3d9c2786b7cd963be84e40a38725R32

**Comment by juzhiyuan** [comment]
https://github.com/apache/incubator-apisix-dashboard/issues/126

**Comment by sshniro** [comment]
Hi @juzhiyuan I would like to attempt this issue.

**Comment by juzhiyuan** [comment]
@sshniro Please send a PR once you have done this work. Here has some tips: please use the config file instead of hard codes. I would recommend using the env[1] when building.

[1] https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by juzhiyuan** [comment]
@sshniro The new dashboard is building on the `next` branch, please use it as base branch.

**Comment by sshniro** [comment]
Hi @juzhiyuan ,

I was trying to use the config file to expose the Key, can I use the config.ts file inside the config dir or create a new one in the src dir?

**Comment by juzhiyuan** [comment]
Yep, you can use the config file under `/config/` directory.
