### ISSUE TITLE
Check the API version for every request

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#139]
In order to make sure the dashboard is using the correct API version, we'd better add the APISIX version in every api response. 

Please 
1. Add the dashboard api version variable in the config file.
2. Check every api response in the `request.ts` file, show a alert when the dashboard version is not compatible with the APISIX version.

**Comment by sshniro** [comment]
Hi @juzhiyuan  shall I give it a try?

**Comment by juzhiyuan** [comment]
Of course you can, but I'm not sure if the APISIX has added the version on admin apis.

@moonming have we manipulated this?

**Comment by sshniro** [comment]
Oh, it seems, the issue is still pending, I'll try to pick on another task for a while.
