### ISSUE TITLE
Adding commit message checker

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#140]
For the quality of every commit message, please add the Commit Message checker just like [1].

[1] https://github.com/vuejs/vue-next/blob/master/scripts/verifyCommit.js

**Comment by sshniro** [comment]
Hi @juzhiyuan where exactly this file should be added? in the CI/CD pipeline?

**Comment by juzhiyuan** [comment]
You could create the file under `ROOT/scripts/`.

**Comment by sshniro** [comment]
Okay, how will the script will be invoked ? in the travis configs ?

**Comment by juzhiyuan** [comment]
`pre-commit`

This script aims to prevent from writing nonsense commit messages.

**Comment by Rapiz1** [comment]
I'd like to take on this by the way if I get selected for OSPP 2020, since this issue is easy to solve. I will soon submit a proposal for https://github.com/apache/incubator-apisix-dashboard/issues/187

**Comment by juzhiyuan** [comment]
OK
