### ISSUE TITLE
Adding Service module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#145]

**Comment by CGerAJ** [comment]
Has this function been written?

**Comment by juzhiyuan** [comment]
Do you mean GSoC?

**Comment by CGerAJ** [comment]
no, I see the project. 
looking at gsoc this year, I'm interested in graphql.

**Comment by juzhiyuan** [comment]
> Has this function been written?
> What should I do if I want to join

You should be familiar with API service module at least, but this module is still under discussion.

**Comment by juzhiyuan** [comment]
Could you please try this issue?

https://github.com/apache/incubator-apisix-dashboard/issues/178
