### ISSUE TITLE
基于淘宝镜像的yarn.lock在Gitlab CI上出现连接问题

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/incubator-apisix-dashboard#150]
请问yarn.lock是否可以自己生成，或者把registry替换成其他地址？

**Comment by juzhiyuan** [comment]
You could use Taobao's mirror.

**Comment by Gary-Airwallex** [comment]
> You could use Taobao's mirror.

现在的问题是我们GCP asia-east上的镜像和淘宝镜像的连接有问题——yarn install报错如下
` [2/4] Fetching packages...
 info There appears to be trouble with your network connection. Retrying...
 info There appears to be trouble with your network connection. Retrying...
 info There appears to be trouble with your network connection. Retrying...
 error An unexpected error occurred: "https://registry.npm.taobao.org/@types/echarts/download/@types/echarts-4.4.1.tgz: unexpected end of file".`
直接运行wget发现连淘宝的镜像很慢。
所以是否有办法替换yarn.lock里的淘宝地址？不使用repo里的yarn.lock的话，yarn install得到的package版本似乎不对

**Comment by juzhiyuan** [comment]
You could remove the yarn.lock and reinstall by using official mirror, don't care about that version.

BTW, the new dashboard is building on next branch, you could use the admin api to operate the APISIX manually.

**Comment by Gary-Airwallex** [comment]
I tried building the new dashboard, but I'm not sure how to add services/routes/plugins with that?And for the issues with taobao mirror which occurred on dashboard v1.0: removing yarn.lock and reinstalling causes the following errors:

     ERROR  Failed to compile with 6 errors                                                                                                                                                        下午1:41:20

     error  in my/path/incubator-apisix-dashboard/src/components/HeaderSearch/index.vue

    ERROR in my/path/incubator-apisix-dashboard/src/components/HeaderSearch/index.vue
    76:18 Generic type 'Fuse<T, O>' requires 2 type argument(s).
        74 |   private options: RouteConfig[] = []
        75 |   private searchPool: RouteConfig[] = []
      > 76 |   private fuse?: Fuse<RouteConfig>
           |                  ^
        77 | 
        78 |   get routes() {
        79 |     return PermissionModule.routes

     error  in my/path/incubator-apisix-dashboard/src/layout/components/TagsView/index.vue

    ERROR in my/path/incubator-apisix-dashboard/src/layout/components/TagsView/index.vue
    207:23 Argument of type 'ITagView' is not assignable to parameter of type 'RawLocation'.
      Type 'ITagView' is not assignable to type 'Location'.
        Types of property 'name' are incompatible.
          Type 'string | null | undefined' is not assignable to type 'string | undefined'.
            Type 'null' is not assignable to type 'string | undefined'.
        205 | 
        206 |   private closeOthersTags() {
      > 207 |     this.$router.push(this.selectedTag)
            |                       ^
        208 |     TagsViewModule.delOthersViews(this.selectedTag)
        209 |     this.moveToCurrentTag()
        210 |   }

     error  in my/path/incubator-apisix-dashboard/src/layout/components/TagsView/index.vue

    ERROR in my/path/incubator-apisix-dashboard/src/layout/components/TagsView/index.vue
    223:25 Argument of type 'ITagView' is not assignable to parameter of type 'RawLocation'.
      Type 'ITagView' is not assignable to type 'Location'.
        221 |     const latestView = visitedViews.slice(-1)[0]
        222 |     if (latestView) {
      > 223 |       this.$router.push(latestView)
            |                         ^
        224 |     } else {
        225 |       // Default redirect to the home page if there is no tags-view, adjust it if you want
        226 |       if (view.name === 'Dashboard') {

     error  in my/path/incubator-apisix-dashboard/src/store/modules/tags-view.ts

    ERROR in my/path/incubator-apisix-dashboard/src/store/modules/tags-view.ts
    55:35 Argument of type 'string | null | undefined' is not assignable to parameter of type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
        53 |   @Mutation
        54 |   private ADD_CACHED_VIEW(view: ITagView) {
      > 55 |     if (this.cachedViews.includes(view.name)) return
           |                                   ^
        56 |     if (!view.meta.noCache) {
        57 |       this.cachedViews.push(view.name)
        58 |     }

     error  in my/path/incubator-apisix-dashboard/src/store/modules/tags-view.ts

    ERROR in my/path/incubator-apisix-dashboard/src/store/modules/tags-view.ts
    57:29 Argument of type 'string | null | undefined' is not assignable to parameter of type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
        55 |     if (this.cachedViews.includes(view.name)) return
        56 |     if (!view.meta.noCache) {
      > 57 |       this.cachedViews.push(view.name)
           |                             ^
        58 |     }
        59 |   }
        60 | 

     error  in my/path/incubator-apisix-dashboard/src/views/login/index.vue

    ERROR in my/path/incubator-apisix-dashboard/src/views/login/index.vue
    105:10 Module '"../../../../../../..my/path/incubator-apisix-dashboard/node_modules/vuex/types"' has no exported member 'Dictionary'.
        103 | import { Component, Vue, Watch } from 'vue-property-decorator'
        104 | import { Route } from 'vue-router'
      > 105 | import { Dictionary } from 'vuex'
            |          ^
        106 | import { Form as ElForm, Input } from 'element-ui'
        107 | import { UserModule } from '@/store/modules/user'
        108 | import { isValidUsername } from '@/utils/validate'

     ERROR  Build failed with errors.
    error Command failed with exit code 1.

And the packages' versions in my generated lock file are different  from the ones in yarn.lock from repo.

**Comment by juzhiyuan** [comment]
I just built one for you.

[dashboard.tar.gz](https://github.com/apache/incubator-apisix-dashboard/files/4317311/dashboard.tar.gz)

**Comment by juzhiyuan** [comment]
@Gary-Airwallex BTW, the new dashboard is under development on the `next` branch, welcome PR or contribution :)
