### ISSUE TITLE
Docker support & pass env when building

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#155]

**Comment by bzp2010** [comment]
Does this mean we will write a `Dockerfile`, to build and run project in docker?

**Comment by juzhiyuan** [comment]
Yep!

**Comment by juzhiyuan** [comment]
Because of different os environments, some users cannot build successfully.

**Comment by bzp2010** [comment]
Since the dashboard will not have a lot of traffic, I think I can use nodejs as the underlying image for program building. Through it, we can realize the function of one key to run a dashboard. 
At the same time, we should add the function of specifying API address of API gateway management through environment variable and dashboard settings.

**Comment by juzhiyuan** [comment]
Ok, I will assign it to you :)

**Comment by bzp2010** [comment]
I write a Dockerfile for test, I found that if the `node_modules` were packed into the image during the build process, the image file would be too large, about 1.3GB.
I think there are two ways to solve this problem

- Write a bash script to transfer the `npm install` process to the `docker run` process

- In the process of building the image, `npm install` is performed, and then the dashboard is compiled and packaged to generate the files for deployment, and the nginx driver is used to access them and delete the node_modules after packaging

I hope to get some suggestions. THX

**Comment by juzhiyuan** [comment]
@bzp2010 Wow, good job! We could only contain those bundled files under dist folder in the image :)

**Comment by juzhiyuan** [comment]
Just write a bash script to only keep files under dist folder?

**Comment by juzhiyuan** [comment]
1. Install `apisix`;
2. Git clone `apisix-dashboard` repo;
3. Build docker image, dashboard files will be bundled in this step;
4. Clean unused files and move bundled files under `apisix/dashboard` folder;

Please note, we use docker just to reduce the compiling error under our Docker env.

**Comment by bzp2010** [comment]
Is this just to compile the program using a unified environment?
I think it is more suitable for docker to deploy dashboard through docker image to provide access.

**Comment by juzhiyuan** [comment]
It's ok to deploy the dashboard inside the docker container, then we should add some configurations in `nginx.conf`, @membphis @moonming what's your opinion?

**Comment by bzp2010** [comment]
Yes.
First, compile the dashboard during image construction, generate dist files, and then put these files into nginx image to expose the port.

> This may take advantage of CI facilities to build and upload images to the docker hub after each commit merge.

**Comment by moonming** [comment]
sure, we can add dashboard in docker image after 1.2 released.

bzp2010 <notifications@github.com> 于 2020年4月16日周四 下午7:46写道：

**Comment by juzhiyuan** [comment]
ok, @bzp2010 Please go ahead for next branch.
