### ISSUE TITLE
Update package.json to the latest upstream version

### ISSUE THREAD

**Issue by bzp2010** [apache/incubator-apisix-dashboard#174]
The package.json of this project is out of date. It has not been updated for 2 months.
It should be upgraded to the latest version upstream with compatibility guaranteed.

**Comment by juzhiyuan** [comment]
next branch? please send a PR.

**Comment by bzp2010** [comment]
Yes, it's next branch.
I used the master branch of Ant Design Pro to create a test project, which refers to the new version of umijs@3, but its documents are not sufficient to ensure the update compatibility. So I temporarily closed this issue, and will submit PR when the documents are complete.
