### ISSUE TITLE
CD for Dashboard

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#176]
Holding for ZEIT's reply

**Comment by bzp2010** [comment]
Have any reply?

**Comment by juzhiyuan** [comment]
I'm not sure if GitHub pages support API rewrite 🤔just holding on and waiting for the Netlify's reply, thanks!

**Comment by juzhiyuan** [comment]
Apache allows us to use Netlify!!! I will configure it those days!

https://issues.apache.org/jira/browse/INFRA-20262

**Comment by bzp2010** [comment]
That's really good. I'm going to try out the features of Netlify.

**Comment by juzhiyuan** [comment]
just for reference
1. https://docs.netlify.com/routing/redirects/rewrites-proxies/
2. https://github.com/ant-design/ant-design-pro/commit/8065f52038b6a4628317a35acecd604d7f9c09e8#diff-5db06fd2327543bbb72119cd1e5761cfL1

**Comment by bzp2010** [comment]
I read the document of the `umi-request` carefully. I found that the `prefix` property can be set when creating the request instance. At the same time, the `prefix` value can be controlled through ENV. It can help us unify the path configuration in the service.

In this way, the `dev` and `deploy` environment do not need to create different service files.

I will do some tests and submit the changes of this part if there are no problems.

**Comment by juzhiyuan** [comment]
Ok, go ahead!
