### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by godsoul** [apache/incubator-apisix-dashboard#179]
login dashboard return 500 Internal Server Error    {"error_msg":"closed"}
apisix version:1.2
bashboard branch: master

**Comment by juzhiyuan** [comment]
Could you please print the Request & Response data as curl?

![image](https://user-images.githubusercontent.com/2106987/79941688-710fa400-8497-11ea-9a5a-c10549d28f19.png)

**Comment by godsoul** [comment]
Request：

Request URL: http://10.225.136.227:9080/apisix/admin/routes
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 10.225.136.227:9080
Referrer Policy: no-referrer-when-downgrade

Request Headers:

GET /apisix/admin/routes HTTP/1.1
Host: 10.225.136.227:9080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
X-API-KEY: edd1c9f034335f136f87ad84b625c8f1
Referer: http://10.225.136.227:9080/apisix/dashboard/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: vue_typescript_admin_access_token=admin-token

Response:

{"error_msg":"closed"}

Response Headers:

HTTP/1.1 500 Internal Server Error
Date: Wed, 22 Apr 2020 05:30:31 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
Server: APISIX web server

**Comment by godsoul** [comment]
curl 'http://10.225.136.227:9080/apisix/admin/routes' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Accept: application/json, text/plain, */*' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36' -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -H 'Referer: http://10.225.136.227:9080/apisix/dashboard/' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'Cookie: vue_typescript_admin_access_token=admin-token' --compressed --insecure

**Comment by godsoul** [comment]
error logs：

2020/04/22 13:51:20 [error] 15992#0: *5158976 [lua] routes.lua:154: failed to get route[/routes]: closed, client: 10.225.11.199, server: , request: "GET /apisix/admin/routes HTTP/1.1", host: "10.225.136.227:9080", referrer: "http://10.225.136.227:9080/apisix/dashboard/"

**Comment by godsoul** [comment]
etcd must support v2 api
