### ISSUE TITLE
Dashboard supports the Grafana.

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix-dashboard#180]
Generally speaking, a dashboard page needs to be able to support viewing and configuring API rules; on the other hand, it also needs to be able to display apisix monitoring data.

Of course, prometheus + grafana has been used as a general solution in the open source monitoring field. The APISIX node itself is a prometheus exporter. I hope the dashboard page can be combined with grafana to display monitoring data

**Comment by juzhiyuan** [comment]
`https://github.com/grafana/grafana` for reference.

**Comment by juzhiyuan** [comment]
Now we could configure the Grafana Metrics in the new Dashboard.

**Comment by juzhiyuan** [comment]
Please note: the grafana address could only be saved in local currently, once the related APIs are ready, we could store it in DB.
