### ISSUE TITLE
failed to add basic-auth plugin

### ISSUE THREAD

**Issue by ywengineer** [apache/incubator-apisix-dashboard#183]
below is basic-auth plugin schema definition
local schema = {
    type = "object",
    properties = {
        username = { type = "string" },
        password = { type = "string" },
    },
    oneOf = {
        {required = {"username", "password"}},
        {required = {}}
    }
}

below is the put request body
{username: "adfa", plugins: {basic-auth: {password: ["asdfa"]}}}

below is the error message
invalid plugins configuration: failed to check the configuration of plugin basic-auth err: property "password" validation failed: wrong type: expected string, got table

the correct put request body must be
{username: "adfa", plugins: {basic-auth: {password: "asdfa"}}}

**Comment by juzhiyuan** [comment]
has been resolve on the new Dashboard.
