### ISSUE TITLE
GitHub Actions for Website

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#213]
Auto PR preview for 

https://github.com/apache/incubator-apisix-website

**Comment by Rapiz1** [comment]
Hi @juzhiyuan Can I take this?

**Comment by juzhiyuan** [comment]
Sure

**Comment by juzhiyuan** [comment]
Please note, this issue is for apisix website[1], not dashboard.

[1] https://github.com/apache/incubator-apisix-website

**Comment by Rapiz1** [comment]
> Please note, this issue is for apisix website[1], not dashboard.
> 
> [1] https://github.com/apache/incubator-apisix-website

Yeah. I have noticed that.

**Comment by juzhiyuan** [comment]
I will explain what this issue should do here later.

**Comment by juzhiyuan** [comment]
Apache APISIX has a website[1][2], which is built on Hugo[3]. 

We used to update this site by following steps:
1. Update codes in the repository[1];
2. Run custom publish shell `publish.sh` locally, and once it's done, it will push built files to the `gh-pages` branch.

So this issue is mainly to use GitHub Action to run publish shell instead of running locally. Because this is not a GSoC task or isrc task, so I'm not sure of its feasibility. If you need any help, please let me know by commenting here or add my wechat JuShaoyao.

[1] https://github.com/apache/incubator-apisix-website
[2] https://apisix.apache.org/
[3] https://gohugo.io/

**Comment by Rapiz1** [comment]
> Apache APISIX has a website[1][2], which is built on Hugo[3].
> 
> We used to update this site by following steps:
> 
>     1. Update codes in the repository[1];
> 
>     2. Run custom publish shell `publish.sh` locally, and once it's done, it will push built files to the `gh-pages` branch.
> 
> 
> So this issue is mainly to use GitHub Action to run publish shell instead of running locally. Because this is not a GSoC task or isrc task, so I'm not sure of its feasibility. If you need any help, please let me know by commenting here or add my wechat JuShaoyao.
> 
> [1] https://github.com/apache/incubator-apisix-website
> [2] https://apisix.apache.org/
> [3] https://gohugo.io/

Thanks for your informative feedback! I managed to set up hugo build on my fork and am now trying to connect to [render](https://render.com/) to set up a PR preview.

>     2. Run custom publish shell `publish.sh` locally, and once it's done, it will push built files to the `gh-pages` branch.

So this task consists of two parts.
1. PR Preview
2. Auto deploy for commits on master

Right?

**Comment by Rapiz1** [comment]
PR Preview is done on my fork. See https://github.com/Rapiz1/incubator-apisix-website/pull/1

**Comment by juzhiyuan** [comment]
🤔We can use Netlify, but I need to apply for access from Apache, once it's approved, I will let you know!

**Comment by juzhiyuan** [comment]
> Apache APISIX has a website[1][2], which is built on Hugo[3].
> 
> We used to update this site by following steps:
> 
> 1. Update codes in the repository[1];
> 2. Run custom publish shell `publish.sh` locally, and once it's done, it will push built files to the `gh-pages` branch.
> 
> So this issue is mainly to use GitHub Action to run publish shell instead of running locally. Because this is not a GSoC task or isrc task, so I'm not sure of its feasibility. If you need any help, please let me know by commenting here or add my wechat JuShaoyao.
> 
> [1] https://github.com/apache/incubator-apisix-website
> [2] https://apisix.apache.org/
> [3] https://gohugo.io/

> Note that PR preview has to be done with CI like render or netlify. 

emmm We don't need a preview for every PR currently, just pushed the bundled files to `gh-pages` branch.

**Comment by juzhiyuan** [comment]
Hi @Rapiz1 , would you mind fixing this issue?

https://github.com/apache/incubator-apisix-dashboard/issues/215
