### ISSUE TITLE
merge PR: only keep `Squash and merge` button

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix-dashboard#252]
![image](https://user-images.githubusercontent.com/6814606/84354268-24bd2680-abf3-11ea-884d-6715fee1fd4e.png)

**Comment by juzhiyuan** [comment]
https://github.com/apache/incubator-apisix-dashboard/commit/2e275c8150b429eaed96add85373e0c84d108f17

Will work when the next branch replaces master
