### ISSUE TITLE
dashboard  Log page need to cancel the default account password 

### ISSUE THREAD

**Issue by niktan** [apache/incubator-apisix-dashboard#26]
dashboard 登录页面取消默认记住的账号密码，并提供修改账号密码的操作。

目前默认是记住的账号密码，且不清楚在哪里修改账号密码。

The dashboard login page cancels the default account password and provides the operation of modifying the account password.

At present, the default is to remember the account password, and it is not clear where to modify the account password.

**Comment by juzhiyuan** [comment]
目前账号密码为模拟数据，暂未开放该接口。
