### ISSUE TITLE
When to provide manager-api and dashboard docker images

### ISSUE THREAD

**Issue by xiangxiren** [apache/incubator-apisix-dashboard#276]

**Comment by gxthrj** [comment]
The official image hasn't been released yet.

You can try to build one directly locally, through these Dockerfiles: 
manager-api: https://github.com/apache/incubator-apisix-dashboard/blob/master/api/Dockerfile
dashboard: https://github.com/apache/incubator-apisix-dashboard/blob/master/Dockerfile

And you can refer to this document to deploy all projects to generate a working environment:
https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/README.md

**Comment by xiangxiren** [comment]
> The official image hasn't been released yet.
> 
> 
> 
> You can try to build one directly locally, through these Dockerfiles: 
> 
> manager-api: https://github.com/apache/incubator-apisix-dashboard/blob/master/api/Dockerfile
> 
> dashboard: https://github.com/apache/incubator-apisix-dashboard/blob/master/Dockerfile
> 
> 
> 
> And you can refer to this document to deploy all projects to generate a working environment:
> 
> https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/README.md


That's exactly what I'm doing right now. If there is an official image, I think it will be easier for novices to get started.

**Comment by gxthrj** [comment]
The official image will be released，When the new version of our dashboard is released.

**Comment by xiangxiren** [comment]
Is there a timetable?

**Comment by membphis** [comment]
I think we'll do this at version `1.5`.

**Comment by xiangxiren** [comment]
> I think we'll do this at version `1.5`.

Okay thank you
