### ISSUE TITLE
manager-api container failed to start

### ISSUE THREAD

**Issue by xiangxiren** [apache/incubator-apisix-dashboard#277]
I used the Dockerfile of manager-api to build an image, and then started a container, but the container did not start normally
![image](https://user-images.githubusercontent.com/12774053/85263332-97ef5400-b4a1-11ea-8d5c-76a98c6a4c6b.png)

The following are my steps：

1. Build the image under the api directory
`docker build -t manager-api:1.0 .`

2. Copy the `build.sh` file, and modify the permissions
    ```
    cp -r tmp/incubator-apisix-dashboard/compose/manager_conf/. example/manager_conf/
    chmod +x ./build.sh
    ```
3. Start a container
    ```
    docker run --name manager-api \
    -v `pwd`/example/manager_conf/build.sh:/root/manager-api/build.sh \
    -p 8080:8080 \
    -d manager-api:1.0
    ```

**Comment by gxthrj** [comment]
Sorry,Here's a detail. Try adding an environment variable like this:
```
docker run --name manager-api \
-v `pwd`/example/manager_conf/build.sh:/root/manager-api/build.sh \
-e ENV=prod \
-p 8080:8080 \
-d manager-api:1.0
```

**Comment by xiangxiren** [comment]
> Sorry,Here's a detail. Try adding an environment variable like this:
> 
> ```
> 
> docker run --name manager-api \
> 
> -v `pwd`/example/manager_conf/build.sh:/root/manager-api/build.sh \
> 
> -e ENV=prod \
> 
> -p 8080:8080 \
> 
> -d manager-api:1.0
> 
> ```


OK, I'll try again tomorrow. thank you

**Comment by xiangxiren** [comment]
I still need help.
I have added the environment variable ENV=prod.A new error has now appeared.

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by gxthrj** [comment]
> I still need help.
> I have added the environment variable ENV=prod.A new error has now appeared.
> 
> ```
> standard_init_linux.go:211: exec user process caused "no such file or directory"
> ```

When ENV=prod, `conf.json` needs to be filled with environment variables
https://github.com/apache/incubator-apisix-dashboard/blob/15d936577d796226d5163af36d92160e693cbcdb/api/build.sh#L21
Please make sure these variables are set in environment variables.

**Comment by xiangxiren** [comment]
Successful deployment, thank you
