### ISSUE TITLE
dashboard load too slow

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix-dashboard#282]
a png file with Request URL: https://user-images.githubusercontent.com/2106987/68087873-a0543980-fe94-11e9-8203-62958ce69ed6.png can not be loaded even after 30s..

![屏幕快照 2020-06-28 下午4 56 05](https://user-images.githubusercontent.com/1818214/85943082-4a229200-b960-11ea-9332-3cced02e09cb.png)

**Comment by totemofwolf** [comment]
```
git clone -b 1.3 https://github.com/apache/incubator-apisix.git /tmp/apisix
cd /tmp/apisix
git submodule init
git submodule update
cd dashboard
yarn
```

**Comment by juzhiyuan** [comment]
This image is blocked by GFW...

BTW, would you like to have a try on the latest dashboard? here is the demo URL: http://dashboard.apisix.dev/
