### ISSUE TITLE
[Dashboard] can't add upstream node

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/incubator-apisix-dashboard#296]
It can't add upstream node when it's format like `api-app-test.example.com`, maybe it's a bug.
![image](https://user-images.githubusercontent.com/5195804/86330923-f2936780-bc7a-11ea-8344-be23fa4c93df.png)

**Comment by juzhiyuan** [comment]
1. The older Dashboard is no longer maintained.
2. Upstream and Consumer module will be added into the new Dashboard next week.

**Comment by UnderTreeTech** [comment]
When do you release the new Dashboard? @juzhiyuan

**Comment by juzhiyuan** [comment]
Not sure when will release the first edition, but changes are made regularly..

**Comment by juzhiyuan** [comment]
New dashboard support this feature currently :)
