### ISSUE TITLE
dashboard error not found plugin name

### ISSUE THREAD

**Issue by gzldx** [apache/incubator-apisix-dashboard#303]
request
/apisix/admin/plugins

400 bad request
<img width="1103" alt="WX20200710-155421@2x" src="https://user-images.githubusercontent.com/2508193/87130544-acb35080-c2c5-11ea-9e5a-b76d3fd7411d.png">

**Comment by juzhiyuan** [comment]
ok, I will take a look in this weekend.

**Comment by gzldx** [comment]
my apisix version: 1.4

find some route are invalid in apisix admin api

/apisix/admin/ssls 404
/apisix/admin/check_ssl_cert 404 

in
/incubator-apisix-dashboard/src/pages/ssl/service.ts

**Comment by juzhiyuan** [comment]
noted, thanks!
