### ISSUE TITLE
the page of routes/list is too wide

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix-dashboard#31]
http://apisix.iresty.com/apisix/dashboard/#/schema/routes/list
![图片](https://user-images.githubusercontent.com/26448043/65015824-34a22580-d955-11e9-82b2-3002de944b18.png)

The page is too wide to see the right button. Instead, just keep the description, host, uri, plug-in information, and click "Edit" to display the other column points.

In addition, the "description" column is too wide and needs to be changed to automatically adjust the width according to the content.

**Comment by eep2019** [comment]
I will do this
