### ISSUE TITLE
Create Routing Pages - Conditions and actions Separation

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix-dashboard#32]
http://apisix.iresty.com/apisix/dashboard/#/schema/routes/create

<img width="477" alt="图片" src="https://user-images.githubusercontent.com/26448043/65016327-8bf4c580-d956-11e9-98cb-feacacb68613.png">

Now conditions and actions are mixed up, and users are not clear. It needs to be clearly separated into two different areas.

**Comment by eep2019** [comment]
working on this
