### ISSUE TITLE
Route cannot enabled plugin

### ISSUE THREAD

**Issue by longshang** [apache/incubator-apisix-dashboard#328]
THX
![image](https://user-images.githubusercontent.com/17903581/88071319-3efd0380-cba6-11ea-901f-985650f9c6af.png)

**Comment by juzhiyuan** [comment]
@longshang Could you please provide more detail? E.g Which plugin could not be enabled? And what are your steps?

**Comment by longshang** [comment]
> @longshang Could you please provide more detail? E.g Which plugin could not be enabled? And what are your steps?

Sorry,its ok!
