### ISSUE TITLE
add support for `vars` in routing conditions 

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix-dashboard#33]
https://github.com/iresty/lua-resty-radixtree#new Add `vars` to the conditions for creating routing pages.

Specific examples in the https://github.com/iresty/lua-resty-radixtree/blob/master/t/vars.t test, search `vars= {` can be, need to support equal, greater, less than, not equal to these operators; vars has supported nginx built-in variables and args, these need to be prompted in the interface, if args necessity is the beginning of `args_`.

**Comment by eep2019** [comment]
I will do this.
