### ISSUE TITLE
Route request params are abnormal, Table 'manager.routes' doesn't exist

### ISSUE THREAD

**Issue by veladeng** [apache/incubator-apisix-dashboard#338]
manager_1     | {"app":"manager-api","level":"error","line":"route/route.go:116","msg":"Route request parameters are abnormal: Error 1146: Table 'manager.routes' doesn't exist","time":"2020-07-24T11:44:01+08:00"}

login into mysql container, mysql did not contain database manager. In dashborad code, can't find create table script.

**Comment by juzhiyuan** [comment]
@gxthrj Please take a look.

**Comment by veladeng** [comment]
Resolved by rebuild dashboard after env cleanning.

**Comment by veladeng** [comment]
@juzhiyuan tks.
