### ISSUE TITLE
route setting  bug

### ISSUE THREAD

**Issue by longshang** [apache/incubator-apisix-dashboard#341]
Set advanced route matching criteria, such as access_ Token on MySQL is correct, but the front end displays access.
mysql  as 
![image](https://user-images.githubusercontent.com/17903581/88616601-253c4e80-d0c7-11ea-8bce-32f987a18819.png)

the front end as
![image](https://user-images.githubusercontent.com/17903581/88616629-35ecc480-d0c7-11ea-89ab-cdfa564d7e86.png)

**Comment by membphis** [comment]
@litesun it seems a bug

**Comment by LiteSun** [comment]
Problem solved.
