### ISSUE TITLE
bug: not support serverless plugin

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix-dashboard#36]

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/71398534-a88e5100-265b-11ea-8d58-a5928a340fdf.png)

![image](https://user-images.githubusercontent.com/2106987/71398695-3c601d00-265c-11ea-87a0-3755d449cc8a.png)

hi @moonming , does it mean there should have a list which could input multiple [function codes](https://github.com/apache/incubator-apisix/blob/master/t/plugin/serverless.t#L254)?

**Comment by moonming** [comment]
yes, it supports multiple functions.

**Comment by juzhiyuan** [comment]
We could use [lua codemirror](https://codemirror.net/mode/lua/index.html) here to support a better code experience.

**Comment by moonming** [comment]
> We could use [lua codemirror](https://codemirror.net/mode/lua/index.html) here to support a better code experience.

which is great.

**Comment by juzhiyuan** [comment]
would be fixed #188
