### ISSUE TITLE
 UI improvement: When the upstream load balancing algorithm is chash, the choice of key can be made into a drop-down list. 

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix-dashboard#37]
schema is here：https://github.com/iresty/apisix/blob/master/lua/apisix/schema_def.lua#L216

![image](https://user-images.githubusercontent.com/6814606/65097171-1d1c7880-d9f9-11e9-83a7-94a75c7e7ba2.png)

**Comment by lilien1010** [comment]
@juzhiyuan  how is the work about this feature going on？

**Comment by lilien1010** [comment]
@juzhiyuan
https://github.com/apache/incubator-apisix/pull/719
after the PR is merged 
I think it support nginx built-in variables like `uri,server_name,server_addr,request_uri,remote_port,remote_addr,query_string,host,hostname,arg_***` , `arg_***` ，so the droplist should be editable & selectable

**Comment by juzhiyuan** [comment]
@lilien1010 Not implemented yet, welcome to send a PR if you could help.

**Comment by lilien1010** [comment]
@juzhiyuan  I think this one it already fix in PR :https://github.com/apache/incubator-apisix-dashboard/pull/65
