### ISSUE TITLE
can add pages and corresponding fuzzy queries

### ISSUE THREAD

**Issue by MorningGlow** [apache/incubator-apisix-dashboard#38]
![F3FAB83A-51E0-478e-B7DE-4EA740092FDC](https://user-images.githubusercontent.com/10829744/65411989-da0b3c80-de20-11e9-8e6b-05c01dc8ae85.png)

If there are too many entries, it is not convenient to see and find, so can we add paging and corresponding fuzzy queries?

**Comment by juzhiyuan** [comment]
Good idea, we may need two query parameters `page` & `limit` for API.

**Comment by moonming** [comment]
agreed.

**Comment by juzhiyuan** [comment]
It has been supported on the new Dashboard.
