### ISSUE TITLE
UI design: create new route

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix-dashboard#41]
> English version:

1. allow to select the filter
1. allow to delete existing conditions
1. the option `host`, `remote address`, and `method`, the user is allowed to enter multiple different values, use space as separator
1. necessary conditions: uri and service, others are optional

> Chinese version:

1. 用户选择需要添加的过滤条件
2. 也可以对已有条件删除
3. 在 host、remote_addr 和 methods 选项中，均允许用户输入多个不同的值，空格分割
4. 必要条件：uri 和 服务，其他均为可选

**Comment by membphis** [comment]
用户按需添加可选字段，对于不关心过滤条件，在界面上完全不显示

![image](https://user-images.githubusercontent.com/6814606/65857708-f6febd00-e396-11e9-8ac9-1098adabf686.png)

**Comment by membphis** [comment]
Option B: 界面上告诉用户所有大的选项，用户手动点击右侧的 CheckBox 决定是否开启这个可选项。

![image](https://user-images.githubusercontent.com/6814606/65857812-2f9e9680-e397-11e9-8e3f-fe407da798eb.png)

**Comment by moonming** [comment]
only `uri` is required, `host`,`remote_addr` and `methods` are optional.
plan B is the fast way to choose conditions.

**Comment by linsir** [comment]
I think the plan A is simpler and easier to understand.

**Comment by totemofwolf** [comment]
选项A 更合适，（必选）的界面适合所有人，隐藏的选项（界面）适合于高端玩家，高端玩家会自行探索 "+"后的奥秘

**Comment by juzhiyuan** [comment]
Please take a look at the new Dashboard.
