### ISSUE TITLE
null value option can be selected in Route Edit Page

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#69]
hi @lilien1010, I found one issue here, the user can select a null value option. 

related PR https://github.com/apache/incubator-apisix-dashboard/pull/62

![image](https://user-images.githubusercontent.com/2106987/68356287-d7547480-014c-11ea-9681-0a63cf4ae348.png)

**Comment by lilien1010** [comment]
ok
