### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by showsmall** [apache/incubator-apisix-dashboard#87]
[root@localhost incubator-apisix-dashboard]# node -v
v10.16.3
[root@localhost incubator-apisix-dashboard]# yarn -v
1.19.2
[root@localhost incubator-apisix-dashboard]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@localhost incubator-apisix-dashboard]# 

 ERROR  Failed to compile with 2 errors                                                                                                                                                                                           9:38:30 PM

 error  in /Data/apisix/incubator-apisix-dashboard/src/components/HeaderSearch/index.vue

ERROR in /Data/apisix/incubator-apisix-dashboard/src/components/HeaderSearch/index.vue
76:18 Generic type 'Fuse<T, O>' requires 2 type argument(s).
    74 |   private options: RouteConfig[] = []
    75 |   private searchPool: RouteConfig[] = []
  > 76 |   private fuse?: Fuse<RouteConfig>
       |                  ^
    77 | 
    78 |   get routes() {
    79 |     return PermissionModule.routes

 error  in /Data/apisix/incubator-apisix-dashboard/src/views/login/index.vue

ERROR in /Data/apisix/incubator-apisix-dashboard/src/views/login/index.vue
105:10 Module '"../../../node_modules/vuex/types"' has no exported member 'Dictionary'.
    103 | import { Component, Vue, Watch } from 'vue-property-decorator'
    104 | import { Route } from 'vue-router'
  > 105 | import { Dictionary } from 'vuex'
        |          ^
    106 | import { Form as ElForm, Input } from 'element-ui'
    107 | import { UserModule } from '@/store/modules/user'
    108 | import { isValidUsername } from '@/utils/validate'

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by juzhiyuan** [comment]
Not building under RedHat yet, will try later.

**Comment by transtone** [comment]
https://github.com/apache/incubator-apisix-dashboard/issues/127
