### ISSUE TITLE
配置路由参数类型错误，urls、hosts选项不能录入

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#88]
![image](https://user-images.githubusercontent.com/28976666/70842443-b32c3780-1e5e-11ea-9cb2-bf4884ebc9c0.png)
配置路由参数类型错误，urls、hosts选项不能录入
类型应该为input，select 的话需要有个可以配置选项的入口

**Comment by juzhiyuan** [comment]
You can input any value directly or select any existing options

**Comment by jiezaizone** [comment]
> You can input any value directly or select any existing options

URLs可以这样录入，但Hosts录入失败，录入值选中后自动情况

**Comment by jiezaizone** [comment]
![image](https://user-images.githubusercontent.com/28976666/70876903-67ac9180-1ff6-11ea-9f06-5aff67274891.png)
urls可以通过录入回车（选中）的方式录入值，hosts则录入失败，会被清空

**Comment by jiezaizone** [comment]
![image](https://user-images.githubusercontent.com/28976666/70877024-bf4afd00-1ff6-11ea-983d-362e0c284472.png)
测试了，hosts要输入域名才可以，ip则不行

**Comment by juzhiyuan** [comment]
Will check today
