### ISSUE TITLE
Plugin proxy-rewrite headers do not edit

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#91]
![image](https://user-images.githubusercontent.com/28976666/71057429-9dd54700-2197-11ea-861d-b8dc1b7b35a0.png)
proxy-rewrite headers 不可编辑

**Comment by juzhiyuan** [comment]
Thanks! Welcome PR!

**Comment by juzhiyuan** [comment]
@moonming @membphis 

![image](https://user-images.githubusercontent.com/2106987/71402861-f493c280-2668-11ea-81b0-cc8edbe8691b.png)

There should have a multiple lines input box, each line contains a Header Key input box and a Header Value input box. I can implement the UI according the specific rule: by checking if the current plugin is  `proxy-rewrite` and if the target property is `headers`, which is not a friendly way.

If we need adjust our API response and returns a more clear type definition? so I can implement a generic component.

**Comment by juzhiyuan** [comment]
would be fixed #188
