### ISSUE TITLE
Routes 不是通过upstream_id 绑定方式添加的Upstreams无法在UI上体现出来

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#92]

**Comment by juzhiyuan** [comment]
Could you give a detailed description please? Some screenshots may help me to get your point.

**Comment by jiezaizone** [comment]
> Could you give a detailed description please? Some screenshots may help me to get your point.

```
curl http://192.168.4.122/apisix/admin/routes/00000000000000000015 -X PUT -d '
{
    "uris": [
        "/*"
    ],
    "hosts": [
        "local-web.com"
    ],
    "plugins": {
        
    },
    "upstream": {
         "nodes": {
            "192.168.4.122:8081": 1,
            "192.168.4.122:8082": 1
        },
        "type": "roundrobin",
        "retries": 2,
        "checks": {
            "active": {
                "http_path": "/status",
                "host": "local-web.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                },
                "req_headers": ["User-Agent: curl/7.29.0"]
            },
            "passive": {
                "healthy": {
                    "http_statuses": [200, 201],
                    "successes": 3
                },
                "unhealthy": {
                    "http_statuses": [500],
                    "http_failures": 3,
                    "tcp_failures": 3
                }
            }
        }
    }
}'
```
![image](https://user-images.githubusercontent.com/28976666/71138637-1f37e280-2247-11ea-981f-16f380716520.png)
比如我执行上述命令，手动添加了负载均衡，并添加了健康检查。在列表中、编辑页面上看不到这两方面的信息（会误以为没有添加）。相对的，在这情况下，我继续编辑页面上修改并保存，如果选了Upstream会覆盖掉我之前定义的负载均衡和健康检查；如果没有修改或修改描述这些数据保存则会报错`invalid configuration: object matches none of the alternatives`
![image](https://user-images.githubusercontent.com/28976666/71138788-835aa680-2247-11ea-90ca-71059017b71d.png)
![image](https://user-images.githubusercontent.com/28976666/71138807-97060d00-2247-11ea-8478-f8d48b32f3a3.png)
![image](https://user-images.githubusercontent.com/28976666/71139002-f532f000-2247-11ea-91cf-080bfc670716.png)

**Comment by juzhiyuan** [comment]
clearly now, thanks for your reply. Currently, dashboard will only show upstreams added by selecting id. I will fix this issue this weekend.

**Comment by jiezaizone** [comment]
> clearly now, thanks for your reply. Currently, dashboard will only show upstreams added by selecting id. I will fix this issue this weekend.

第二点：在路由上已经配置有hosts，checks. active 还需要配置host 是否显得有点儿多余／重复？安装我的理解，它既然已经绑在在路由上，应该就对该路由上的hosts都生效才对

**Comment by juzhiyuan** [comment]
Hi @membphis , could you help to involve this issue?
