### ISSUE TITLE
bug: SSL certs key content should be kept secret in dashboard

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix-dashboard#93]
### Environment

* apisix version (cmd: `apisix version`): 0.9
* OS: alpine 3.7

### What's the expected result?

![11576646267_ pic](https://user-images.githubusercontent.com/1818214/71064620-7b005e00-21aa-11ea-86f7-a58ff39ba1ee.jpg)

**Comment by juzhiyuan** [comment]
@totemofwolf  API CAN NOT response the content of KEY to /api/admin/

**Comment by juzhiyuan** [comment]
In my opinion, I think this issue can be resolved by API, when fetching the existing SSL certificate info, api could not send back the cert content.

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/incubator-apisix-dashboard/issues/93
