### ISSUE TITLE
Plugin serverless-pre-function function不可编辑

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#94]
![image](https://user-images.githubusercontent.com/28976666/71138385-480ba800-2246-11ea-8c02-075c8cde119b.png)
Plugin serverless-pre-function function不可编辑

**Comment by juzhiyuan** [comment]
It's caused by unset value type, welcome PR.

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/incubator-apisix-dashboard/issues/36

**Comment by juzhiyuan** [comment]
would be fixed #188
