### ISSUE TITLE
no need to support select input for host and uri.

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix-dashboard#95]
I think the same `uri` will hardly appear in different `route`.

![image](https://user-images.githubusercontent.com/6814606/71142178-92deed00-2251-11ea-84a5-576eece20d23.png)

**Comment by membphis** [comment]
@lilien1010 What do you think?

**Comment by juzhiyuan** [comment]
This component is allowed to create new items

https://www.iviewui.com/components/select

![image](https://user-images.githubusercontent.com/2106987/71142537-a474c480-2252-11ea-90ae-bc25e3a23e03.png)

**Comment by jiezaizone** [comment]
> I think the same `uri` will hardly appear in different `route`.
> 
> ![image](https://user-images.githubusercontent.com/6814606/71142178-92deed00-2251-11ea-84a5-576eece20d23.png)

会有这个需求的，像我公司的系统由好几个子系统组成，共享同一个域名，就是通过路由规则来区分转发的。
