### ISSUE TITLE
Update the package version of serialize-javascript

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix-dashboard#97]

**Comment by moonming** [comment]
Upgrade serialize-javascript to version 2.1.1 or later. For example:

serialize-javascript@^2.1.1:
  version "2.1.1"

**Comment by juzhiyuan** [comment]
After several searches, this dependency is related to `vue/cli-service`， the better way to fix this is to upgrade the vue-cli dependency. Because it's not an urgent issue, we could do it when we are ready to upgrade vue-cli tools.
