### ISSUE TITLE
Plugin ip-restriction 的黑白名单无法编辑

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix-dashboard#98]
![image](https://user-images.githubusercontent.com/28976666/71162075-7ceb1f80-2285-11ea-8464-1d3d9e175203.png)

**Comment by juzhiyuan** [comment]
hi @membphis , according to the [description](https://github.com/apache/incubator-apisix/blob/master/t/plugin/ip-restriction.t#L193), when I try to use ip-restriction plugin, error occurred:

![image](https://user-images.githubusercontent.com/2106987/71400202-f22d6a80-2660-11ea-931f-decd4772249f.png)

![image](https://user-images.githubusercontent.com/2106987/71400206-f6f21e80-2660-11ea-884f-998517cbb967.png)

I'm not sure if I misunderstand the usage of this plugin.

**Comment by moonming** [comment]
no `upstream` section?

**Comment by juzhiyuan** [comment]
> no `upstream` section?

Create succeed when I choose one upstream!!

**Comment by moonming** [comment]
looks like we need one more friendly way

**Comment by juzhiyuan** [comment]
Yep, I will create a new issue.
